name: imaging-python-course
channels:
  - conda-forge
  - nvidia
  - nodefaults
dependencies:
  - python
  - scikit-image
  - ipykernel
  - matplotlib
  - seaborn
  - statannotations
  - pandas
  - openpyxl
  - numba
  - pytorch
  - cuda-toolkit=12.4.0
  - cellpose<=3
  - napari
  - laptrack
  - pip
  - pip:
    - bioio
    - bioio-nd2
    - bioio-tifffile
    - bioio-czi
    - bioio-lif

