name: imaging-python-course
channels:
  - pytorch-nightly
  - conda-forge
dependencies:
  - python
  - pip
  - pytorch-nightly::pytorch
  - pytorch-nightly::torchvision
  - conda-forge::ipykernel
  - conda-forge::matplotlib
  - conda-forge::pandas
  - conda-forge::seaborn
  - conda-forge::scipy
  - conda-forge::scikit-image
  - conda-forge::openpyxl
  - conda-forge::xmlschema
  - conda-forge::bioformats_jar
  - conda-forge::nd2
  - conda-forge::cellpose
  - conda-forge::statannotations
  - conda-forge::ipywidgets
  - conda-forge::mpl-interactions
  - conda-forge::trackpy
  - conda-forge::tifffile
  - conda-forge::readlif
  - conda-forge::aicsimageio
