name: imaging-python-course
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pip
  - pytorch::pytorch
  - pytorch::pytorch-cuda=11.7
  - pytorch::torchvision
  - ipykernel
  - matplotlib
  - pandas
  - seaborn
  - scipy
  - scikit-image
  - openpyxl
  - bioformats_jar
  - pip:
      - cellpose
      - ipywidgets
      - ipyfilechooser
      - mpl-interactions[jupyter]
      - trackpy
      - nd2
      - tifffile
      - readlif
      - aicspylibczi
      - aicsimageio
