name: imaging-python-course
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - scikit-image
  - ipykernel
  - matplotlib
  - pandas
  - seaborn
  - openpyxl
  - pytest
  - nbformat
  - nbconvert
  - pip
  - pip:
      - torch
      - torchvision
      - cellpose<=3
      - mpl_interactions[jupyter]
      
