name: imaging-python-course
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pytorch
  - pytorch-cuda=11.7
  - torchvision
  - ipykernel
  - matplotlib
  - pandas
  - seaborn
  - scipy
  - scikit-image
  - openpyxl
  - xmlschema
  - bioformats_jar
  - nd2
  - cellpose
  - statannotations
  - ipywidgets
  - mpl-interactions
  - trackpy
  - tifffile
  - readlif
  - aicsimageio
