name: imaging-python-course
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - scikit-image
  - ipykernel
  - matplotlib
  - pandas
  - seaborn
  - openpyxl
  - pytorch
  - torchvision
  - numba
  - cellpose<=3
  - napari
  - pip
  - pip:
    - bioio
    - bioio-nd2
    - bioio-tifffile
    - bioio-czi
    - bioio-lif

