name: imaging-python-course
channels:
  - conda-forge
dependencies:
  - python=3.10
  - scikit-image
  - ipykernel
  - matplotlib
  - seaborn
  - statannotations
  - pandas
  - openpyxl
  - numba
  - pytorch
  - pytorch-gpu
  - torchvision
  - cellpose<4
  - napari
  - laptrack
  - pytest
  - pip
  - pip:
    - bioio
    - bioio-nd2
    - bioio-tifffile
    - bioio-czi
    - bioio-lif
