name: imaging-python-course
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - scikit-image
  - ipykernel
  - matplotlib
  - seaborn
  - pandas
  - openpyxl
  - numba
  - cellpose<=3
  - napari
  - laptrack
  - pip
  - pip:
    - bioio
    - bioio-nd2
    - bioio-tifffile
    # - bioio-czi
    - bioio-lif
    - torch
    - torchvision