name: imaging-python-course
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - scikit-image
  - ipykernel
  - matplotlib
  - pandas
  - seaborn
  - openpyxl
  - pytest
  - nbformat
  - nbconvert
  - pip
  - pytorch
  - torchvision
  - cellpose<=3
  - pip
  - pip:
      - mpl_interactions[jupyter]